name: pre_booking
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  convex_bottom_bar: ^3.2.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  readmore: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.regular.ttf
